name: Build Data

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Run build index script
      run: cd tools/index-builder; npm i; npm start

    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions