name: Sync Templates to Old Repository

on:
  push:
    paths:
      - 'templates/**'
      - '.github/workflows/**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout new repository
        uses: actions/checkout@v4

      - name: Clone old repository
        run: |
          git clone --branch main https://x-access-token:${{ secrets.OLD_REPO_TOKEN }}@github.com/Dituon/petpet.git old-repo

      - name: Sync templates to old repository
        run: |
          rsync -av --delete templates/ old-repo/data/xmmt.dituon.petpet/

      - name: Extract commit history
        run: |
          git log --format='%H %an <%ae>' templates/ > commit-history.log

      - name: Commit and push changes
        working-directory: old-repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/xmmt.dituon.petpet
          if git diff --cached --quiet; then
            echo "No changes to sync"
          else
            read -r COMMIT_HASH AUTHOR <<< $(head -n 1 ../commit-history.log)
            AUTHOR_NAME=$(echo "$AUTHOR" | sed 's/ <.*//')
            AUTHOR_EMAIL=$(echo "$AUTHOR" | sed 's/.*<\(.*\)>/\1/')
            git commit --author="$AUTHOR_NAME <$AUTHOR_EMAIL>" \
                      -m "Sync templates from petpet-templates repository ($COMMIT_HASH)"
            git push https://x-access-token:${{ secrets.OLD_REPO_TOKEN }}@github.com/Dituon/petpet.git main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.OLD_REPO_TOKEN }}
